package com.immersio.scenarios.service;
import com.immersio.scenarios.api.dto.*; import com.immersio.scenarios.domain.*; import com.immersio.scenarios.repository.*; import com.immersio.shared.exception.ResourceNotFoundException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class ScenarioService { private final ScenarioRepository scenarios; private final ScenarioItemRepository items; private final ScenarioSessionRepository sessions; private final SessionMessageRepository messages; private final ScenarioLlmClient llm; public ScenarioService(ScenarioRepository s,ScenarioItemRepository i,ScenarioSessionRepository ss,SessionMessageRepository m,ScenarioLlmClient l){scenarios=s;items=i;sessions=ss;messages=m;llm=l;}
 @Transactional(readOnly=true) public List<ScenarioDto> getScenarios(){return scenarios.findByDeletedFalseOrderByTitleAsc().stream().map(this::dto).toList();} @Transactional(readOnly=true) public ScenarioDto getScenarioById(UUID id){return dto(scenarios.findByIdAndDeletedFalse(id).orElseThrow(()->new ResourceNotFoundException("Scenario not found.")));}
 @Transactional public StartSessionResponse startSession(UUID user,StartSessionRequest r){Scenario s=scenarios.findByIdAndDeletedFalse(r.scenarioId()).orElseThrow(()->new ResourceNotFoundException("Scenario not found."));var x=sessions.save(new ScenarioSession(user,s.getId()));var msg=messages.save(new SessionMessage(x.getId(),"assistant",s.getInitialMessage()));return new StartSessionResponse(x.getId(),s.getInitialMessage(),dto(s),List.of(md(msg)));}
 @Transactional public ChatOutputResponse sendMessage(UUID user,UUID id,ChatInputRequest r){var s=sessions.findByIdAndUserId(id,user).orElseThrow(()->new ResourceNotFoundException("Session not found."));var in=messages.save(new SessionMessage(id,"user",r.message()));var out=messages.save(new SessionMessage(id,"assistant",llm.reply("You are a language tutor.",List.of(Map.of("role","user","content",r.message())))));return new ChatOutputResponse(out.getText(),new CorrectionResultDto(out.getCorrectionText(),out.getCorrectionExplanation()),"idle",md(out));}
 @Transactional public FinishSessionResponse completeSession(UUID user,UUID id){var s=sessions.findByIdAndUserId(id,user).orElseThrow(()->new ResourceNotFoundException("Session not found."));s.finish("Good work! Keep practicing.");sessions.save(s);return new FinishSessionResponse(s.getFeedback(),List.of(),id,true);}
 public Map<String,Object> generateCustomFlashcards(UUID user,UUID id,GenerateFlashcardsRequest r){sessions.findByIdAndUserId(id,user).orElseThrow(()->new ResourceNotFoundException("Session not found."));return Map.of("message","Flashcards generated", "count",0);}
 @Transactional public ScenarioDto createScenario(CreateScenarioDto r){return dto(scenarios.save(new Scenario(r.title(),r.language(),r.level(),r.category(),r.description(),r.duration(),r.imageUrl(),r.contextPrompt(),r.initialMessage(),r.avatarUrl())));}
 @Transactional public ScenarioDto updateScenario(UUID id,CreateScenarioDto r){var s=scenarios.findByIdAndDeletedFalse(id).orElseThrow(()->new ResourceNotFoundException("Scenario not found."));s.update(r.title(),r.language(),r.level(),r.category(),r.description(),r.duration(),r.imageUrl(),r.contextPrompt(),r.initialMessage(),r.avatarUrl());return dto(scenarios.save(s));}
 @Transactional public void deleteScenario(UUID id){var s=scenarios.findByIdAndDeletedFalse(id).orElseThrow(()->new ResourceNotFoundException("Scenario not found."));s.delete();scenarios.save(s);} @Transactional public ScenarioItemDto addScenarioItem(UUID id,CreateScenarioItemDto r){var s=scenarios.findByIdAndDeletedFalse(id).orElseThrow(()->new ResourceNotFoundException("Scenario not found."));return item(items.save(new ScenarioItem(s,r.name(),r.price(),r.imageUrl(),r.icon())));}
 public void seedScenarios(){} private ScenarioDto dto(Scenario s){return new ScenarioDto(s.getId(),s.getTitle(),s.getLanguage(),s.getLevel(),s.getCategory(),s.getDescription(),s.getRating(),s.getDuration(),s.getImageUrl(),s.getContextPrompt(),s.getInitialMessage(),s.getAvatarUrl(),s.isNavigation(),s.getVoiceId(),s.getEmotionsJson(),s.getGender(),s.getDefaultEmotion(),s.getItems().stream().map(this::item).toList());} private ScenarioItemDto item(ScenarioItem x){return new ScenarioItemDto(x.getId(),x.getScenarioId(),x.getName(),x.getPrice(),x.getImageUrl(),x.getIcon());} private SessionMessageDto md(SessionMessage x){return new SessionMessageDto(x.getId(),x.getSessionId(),x.getSenderRole(),x.getText(),x.getSentAt(),x.getCorrectionText(),x.getCorrectionExplanation());}}
