package com.immersio.scenarios.domain;
import jakarta.persistence.*; import java.util.*;
@Entity @Table(name="\"Scenarios\"")
public class Scenario {
 @Id @GeneratedValue(strategy=GenerationType.UUID) @Column(name="\"Id\"") private UUID id;
 @Column(name="\"Title\"",nullable=false,length=200) private String title; @Column(name="\"Language\"",nullable=false) private String language; @Column(name="\"Level\"",nullable=false) private String level; @Column(name="\"Category\"",nullable=false) private String category; @Column(name="\"Description\"",nullable=false,length=1000) private String description; @Column(name="\"Rating\"",nullable=false) private double rating=5; @Column(name="\"Duration\"",nullable=false) private String duration; @Column(name="\"ImageUrl\"",nullable=false,length=1000) private String imageUrl; @Column(name="\"ContextPrompt\"",nullable=false,length=4000) private String contextPrompt; @Column(name="\"InitialMessage\"",nullable=false,length=1000) private String initialMessage; @Column(name="\"AvatarUrl\"",nullable=false,length=1000) private String avatarUrl; @Column(name="\"IsNavigation\"") private boolean navigation; @Column(name="\"VoiceId\"") private String voiceId; @Column(name="\"EmotionsJson\"") private String emotionsJson; @Column(name="\"Gender\"") private String gender; @Column(name="\"DefaultEmotion\"") private String defaultEmotion; @Column(name="\"IsDeleted\"") private boolean deleted;
 @OneToMany(mappedBy="scenario",fetch=FetchType.LAZY,cascade=CascadeType.ALL) private List<ScenarioItem> items=new ArrayList<>(); protected Scenario(){}
 public Scenario(String title,String language,String level,String category,String description,String duration,String imageUrl,String contextPrompt,String initialMessage,String avatarUrl){this.title=title;this.language=language;this.level=level;this.category=category;this.description=description;this.duration=duration;this.imageUrl=imageUrl;this.contextPrompt=contextPrompt;this.initialMessage=initialMessage;this.avatarUrl=avatarUrl;}
 public UUID getId(){return id;} public String getTitle(){return title;} public String getLanguage(){return language;} public String getLevel(){return level;} public String getCategory(){return category;} public String getDescription(){return description;} public double getRating(){return rating;} public String getDuration(){return duration;} public String getImageUrl(){return imageUrl;} public String getContextPrompt(){return contextPrompt;} public String getInitialMessage(){return initialMessage;} public String getAvatarUrl(){return avatarUrl;} public boolean isNavigation(){return navigation;} public String getVoiceId(){return voiceId;} public String getEmotionsJson(){return emotionsJson;} public String getGender(){return gender;} public String getDefaultEmotion(){return defaultEmotion;} public boolean isDeleted(){return deleted;} public List<ScenarioItem> getItems(){return items;}
 public void update(String title,String language,String level,String category,String description,String duration,String imageUrl,String contextPrompt,String initialMessage,String avatarUrl){this.title=title;this.language=language;this.level=level;this.category=category;this.description=description;this.duration=duration;this.imageUrl=imageUrl;this.contextPrompt=contextPrompt;this.initialMessage=initialMessage;this.avatarUrl=avatarUrl;} public void delete(){deleted=true;}
}
