-- V2__modulith_event_publication.sql
-- Spring Modulith JPA event-publication registry (entity:
-- org.springframework.modulith.events.jpa.JpaEventPublication). The .NET-era
-- schema has no equivalent table, and Hibernate runs ddl-auto=validate at
-- startup, so this table must exist before boot.
--
-- DDL is NOT hand-written: it was generated by Hibernate 7.4 itself
-- (spring-boot:run with ddl-auto=update against an empty PostgreSQL 16) and
-- frozen here verbatim, so validation passes by construction — both on the
-- existing production database (V1 baselined → V2 is the first migration to
-- run) and on fresh installs (V1 then V2).

CREATE TABLE IF NOT EXISTS event_publication (
    id uuid NOT NULL,
    completion_attempts integer NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255) NOT NULL,
    last_resubmission_date timestamp(6) with time zone,
    listener_id character varying(255) NOT NULL,
    publication_date timestamp(6) with time zone NOT NULL,
    serialized_event character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT event_publication_status_check CHECK (((status)::text = ANY ((ARRAY['PUBLISHED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'RESUBMITTED'::character varying])::text[])))
);

ALTER TABLE ONLY event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);
