name: Test Self-Hosted Runner
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - run: echo "Runner=${{ runner.name }} OS=${{ runner.os }} Host=$(hostname)"
  
